version: '3'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    expose:
      - 5432/TCP
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
