# fly.toml app configuration file generated for the-learnary on 2024-03-14T22:11:25+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'the-learnary'
primary_region = 'otp'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 4321
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
